export const cuisineList = [
    "Italian",
    "Chinese",
    "Mexican",
    "Indian",
    "Thai",
    "French",
    "Japanese",
    "Greek",
    "Spanish",
    "American",
    "Mediterranean",
    "Caribbean",
    "Middle Eastern",
    "Vietnamese",
    "Korean",
    "Brazilian",
    "African",
    "Russian",
    "Indonesian",
    "Malaysian",
    "Filipino",
    "Turkish",
    "Ethiopian",
    "Polish",
    "Irish",
    "German",
    "British",
    "Cajun",
    "Peruvian",
    "Swiss",
    "Why would u wanna click this",
    "wait what",
];